### ISSUE TITLE
Build font failed after updating project-template version

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/googlefonts-project-template#116]
I [updated](https://github.com/weiweihuanghuang/fragment-mono/commit/64d16d8f5819fb511a4e39565325149a92604896) my [Fragment Mono](https://github.com/weiweihuanghuang/fragment-mono)'s googlefonts-project-template version (unclear what version but from the version at Dec 16, 2022 to Aug 18, 2023) and the build now breaks.

The error messages in the [build log](https://github.com/weiweihuanghuang/fragment-mono/actions/runs/5898273059/job/15999087238#step:10:968) seems to be about compatibility checks. In my [config file](https://github.com/weiweihuanghuang/fragment-mono/blob/main/sources/config.yaml) I don't have variable fonts enabled and I don't have any interpolated instances. Whats going on?

**Comment by simoncozens** [comment]
Change that False (python-style) to a false (YAML-style) and try again?

**Comment by weiweihuanghuang** [comment]
Still failed the compatibility check that it doesn't need to do:
https://github.com/weiweihuanghuang/fragment-mono/actions/runs/5910898794/job/16032922260#step:10:143

**Comment by weiweihuanghuang** [comment]
Any clues @simoncozens ?

**Comment by simoncozens** [comment]
Sorry, I've been on holiday. I'll take a look.

**Comment by simoncozens** [comment]
Ah, there's another builder config option:

* ``checkCompatibility``: Enable fontmake Multiple Master compatibility checking. Defaults to ``true``.

I think the problem is that in general we can't tell whether or not instances are interpolated, and so we assume they are. (We don't really expect fonts to have incompatible masters in them these days, and generally we keep italic and regular in separate sources.)
