### ISSUE TITLE
`make build`: Nothing to be done for `build'.

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/googlefonts-project-template#141]
Can't get the fonts to build locally anymore?

**Comment by simoncozens** [comment]
Not really enough information to go off (which repo? what have you done? etc.), but that message is shorthand for "I've already built these fonts, and I wrote a file called `build.stamp` to remember when I built them. All of your sources are older than `build.stamp`, which means nothing has changed since the last build, so there's no point me building the font again."

You can either make changes to your font and save it, then try again; or delete build.stamp and try again.

**Comment by weiweihuanghuang** [comment]
Thanks that cleared it up, I didn't know what thatmessage meant!
