### ISSUE TITLE
Rename this repo to something that makes sense to users in 2022+

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlefonts-project-template#66]
This repo's name was coined 10+ years ago, and I don't think it makes sense to users. 

`repo-template-batteries-included`

`repo-template-fully-loaded`

`repo-template-default`

Other ideas? :)

I recently made https://github.com/googlefonts/blank-ofl-project and I propose to rename that to match too, eg

`repo-template-blank`

**Comment by simoncozens** [comment]
"repo-template" etc. too generic?

But these kind of templates on GitHub often end "-template", "-boilerplate", or "-starter".
 "ofl-project-starter"? "libre-font-starter"?

**Comment by davelab6** [comment]
I expect /gf/ufr is GF specific, so `gf-project-template` and `ofl-project-template`?

**Comment by simoncozens** [comment]
I don't think this repo is particularly GF specific. It's a useful repository layout for anyone doing an OFL project, whether they're aiming at being onboarded to GF or not.

**Comment by davelab6** [comment]
`ofl-project-template` & `ofl-project-template-blank`?

**Comment by RosaWagner** [comment]
@simoncozens Actually it is using fontbakery check-google profile + gftools builder that is enforcing GF font requirements. It looks pretty GF related, no? Also GF is like a brand, so calling it GF-template or something could mean "from GF" and not necessarily "for GF". 

For the blank one, it is obviously not even from GF since it only has a License (but reading the license, would also need the AUTHORS.txt and this kind of stuff), so could be indeed `ofl-project-template`.

**Comment by simoncozens** [comment]
Good arguments! But (and I know I'm bikeshedding here) I prefer to avoid acronyms where possible, because they take people a bit longer to understand especially if their first language is not English. I'd be happy with `google-fonts-project-template`.

`ofl-project-template` is fine with me. (I've realised I'm going to need a `noto-project-template` as well...)

**Comment by vv-monsalve** [comment]
I was writing: 
I don't see any harm in the name is specific. It is hosted by `googlefonts`, the specific name would be useful when referring to it in our documentation, and the name doesn't prevent it to be used by other users.

`google-fonts-project-template` is long but sounds good, avoiding acronyms would also clarify the specificity of the "font" project

**Comment by davelab6** [comment]
Its now renamed `https://github.com/googlefonts/googlefonts-project-template`

**Comment by davelab6** [comment]
https://github.com/googlefonts/googlefonts-project-template-blank also renamed
