### ISSUE TITLE
Release job doesn't run + /fonts didn't get added to repo after action is run

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/googlefonts-project-template#87]
I just uploaded a repo using the gf project template:
https://github.com/weiweihuanghuang/fragment-mono/

It says I got a [fail](https://github.com/weiweihuanghuang/fragment-mono/actions/runs/3179581485) but I think that is not an actual fail as @eliheuer pointed out [here](https://github.com/googlefonts/googlefonts-project-template/issues/81).

It didn't run the `release` job though, and the /fonts folder didn't get uploaded. Did I do something wrong?

**Comment by simoncozens** [comment]
You're correct that this isn't a fail. Fontbakery returned some errors, and the error is to notify you of that; but the result of the job went ahead. The "release" job is only run when you create a GitHub release; it creates the zip file of fonts and adds it to the release. Neither of these things update the fonts/ folder.

We should:

* Rewrite the action so that it returns a clearer error message from fontbakery, making it obvious the job succeeded but with fontbakery fails.
* Explain how releases work and how the fonts/ folder is manually managed.

**Comment by eliheuer** [comment]
> Rewrite the action so that it returns a clearer error message from fontbakery, making it obvious the job succeeded but with fontbakery fails.

I'm working on a PR fixing this today, but no big deal if Simon beats me to it.

**Comment by simoncozens** [comment]
Not planning to work on it any time soon, hands full with other stuff...

**Comment by weiweihuanghuang** [comment]
So is the fonts folder normally ignored then?

**Comment by eliheuer** [comment]
[gftools packager](https://googlefonts.github.io/gf-guide/package.html) uses the `fonts` directory to make pull requests to [google/fonts](https://github.com/google/fonts). I add the `fonts` directory manually after the version 1.000 release.

In development before a version 1.000 release, I just get the fonts from the GitHub Actions build artifacts, and I always put in the main README that font files can be downloaded from the actions tab.

**Comment by eliheuer** [comment]
Ok, I made a PR fixing the error: https://github.com/googlefonts/googlefonts-project-template/pull/93

I can also try to do this and close this issue if the PR is merged.
> Explain how releases work and how the fonts/ folder is manually managed.
